apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: sunaina0510/backendimage:latest
        ports:
        - containerPort: 3000
