apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-f
  template:
    metadata:
      labels:
        app: nodejs-f
    spec:
      containers:
      - name: nodejs-f
        image: sunaina0510/frontendimage:latest
        ports:
        - containerPort: 3000
