name: Deploy Node.js Application
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker images
        run: |
          docker build -t backendimage ./Application-Code/backend
          docker build -t frontendimage ./Application-Code/frontend

      - name: Push Docker images
        run: |
          docker tag backendimage ${{ secrets.DOCKER_USERNAME }}/backendimage:latest
          docker tag frontendimage ${{ secrets.DOCKER_USERNAME }}/frontendimage:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/backendimage:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontendimage:latest

      - name: Start Minikube
        run: |
         minikube start

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/backend-deployment.yml
          kubectl apply -f k8s/frontend-deployment.yml
          kubectl apply -f k8s/backend-service.yml
          kubectl apply -f k8s/frontend-service.yml

